### ISSUE TITLE
No GPU usage percentage when using MangoHUD with the OpenGL drivers under emulation

### ISSUE THREAD

**Issue by m1m1k4tz** [AsahiLinux/muvm#113]
![Screenshot from 2024-11-26 04-41-12](https://github.com/user-attachments/assets/9077c8da-486e-4236-aa2d-4916b461a276)

### Steps to reproduce
Install muvm

Install MangoHud

Compile the latest Box64 from source and install it

Download the latest Kronek Wine WoW64 build

Install the symlinks

```
export WINEBIN = ~/Downloads/wine-*****-amd64-wow64/bin
sudo ln -s $WINEBIN/wine /usr/local/bin/wine
sudo ln -s $WINEBIN/wine64 /usr/local/bin/wine64
sudo ln -s $WINEBIN/wineboot /usr/local/bin/wineboot
sudo ln -s $WINEBIN/winecfg /usr/local/bin/winecfg
sudo ln -s $WINEBIN/wineserver /usr/local/bin/wineserver
sudo chmod +x /usr/local/bin/wine /usr/local/bin/wine64 /usr/local/bin/wineboot /usr/local/bin/winecfg /usr/local/bin/wineserver
```

Install cabextract

Install corefonts with winetricks

Install the Steam executable and it should just work

Finally run Steam with muvm mangohud --dlsym box64 wine 'C:\Program Files (x86)\Steam\steam.exe'

[mangohud.txt](https://github.com/user-attachments/files/17921005/mangohud.txt)

**Comment by alyssarosenzweig** [comment]
This is not a muvm bug. It doesn't work natively either.
