### ISSUE TITLE
VM crashes after suspend

### ISSUE THREAD

**Issue by alyssarosenzweig** [AsahiLinux/muvm#56]
If I open Steam and idle long enough for Plasma to autosuspend the machine (or at least turn off my monitor), when I unsuspend & turn the screen back on & unlock Plasma, the VM has crashed with

12sommelier: ../sommelier.cc:956: void sl_registry_remover(void*, wl_registry*, uint32_t): Assertion `0' failed.
(EE) failed to write to Xwayland fd: Broken pipe

Hopefully that's fixable..?
this is on a Mac Studio, not sure if reproducible on the laptops

**Comment by alyssarosenzweig** [comment]
update: it's not suspend that's the problem, it's turning the monitor off and on (equivalent to unplugging the HDMI cable and replugging, I think). should repro on a mac mini.

**Comment by jannau** [comment]
The assert in question is at the [end](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/vm_tools/sommelier/sommelier.cc#956) of sommelier's `wl_registry_listener.global_remove` callback. It is more of a debug feature for ChromeOS and should not be active when used with random wayland compositors. Sommelier's remove callback matches exhaustively against its used interface. That means if a general purpose compositor implements a global interface that sommelier doesn't use it will sooner or later always run into this assert.
Does it make sense to submit changes to chromiumos/vm_tools? In any case this needs to at least move to Fedora's bugzilla.

**Comment by jannau** [comment]
fix in https://src.fedoraproject.org/rpms/chromiumos-platform/pull-request/3

**Comment by jannau** [comment]
fixed by sommelier-0~20240902git67bc17e-4

**Comment by alyssarosenzweig** [comment]
Awesome, thanks :smile:

**Comment by alyssarosenzweig** [comment]
Confirmed fixed
