### ISSUE TITLE
Steam game download takes all 16GB of memory + swap before crashing

### ISSUE THREAD

**Issue by dev-sda1** [AsahiLinux/muvm#78]
Hi all, currently using the new steam stuff that's just come out and it's incredible work. Currently having an issue I think where a game download causes muvm's memory usage to slowly creep up over the course of 15-25 mins, consume all the system RAM and swap, before the memory manager kicks in and SIGKILLS it.

It's an M1 Pro 10 core with 16GB of RAM attempting to currently download Elite: Dangerous. Apologies if this isn't the case.

![image](https://github.com/user-attachments/assets/192b10df-43e0-4565-bf39-3991aa00c500)

**Comment by teohhanhui** [comment]
Try with 16G zram for now...

**Comment by dev-sda1** [comment]
Managed to avoid most of the crashes since by running ``steam --ram 12397`` (13gb) or ``steam --ram 13351`` (14gb)
