### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jonathf** [AsahiLinux/muvm#84]
I'm trying to build muvm on my Asahi linux installation and I am getting the following error:

    muvm.c6c200dfed6eeab0-cgu.00:(.text._ZN4muvm4main17hb307d7d97b619470E+0xb40): undefined reference to `krun_add_disk'
    collect2: error: ld returned 1 exit status

Both `libkrun` and `libkrunfw` are installed and available from `/usr/local/lib64` so I tried running with:

    RUSTFLAGS="-C link-arg=-L/usr/local/lib64/,-lkrunfw,-lkrun" cargo build
    
but I got the same result.

I am unsure here if this is a linker issue, or if the dependencies are broken/incorrectly configured.

Related: Is there any installation instruction that I should be aware of for this project?

**Comment by teohhanhui** [comment]
@jonathf:
> muvm.c6c200dfed6eeab0-cgu.00:(.text._ZN4muvm4main17hb307d7d97b619470E+0xb40): undefined reference to `krun_add_disk'

You need libkrun >= 1.9.5

**Comment by jonathf** [comment]
libkrun is built from newest source and identifies as version 1.9.5.

**Comment by rowanG077** [comment]
You need to pass `BLK=1` to cmake.

**Comment by jonathf** [comment]
Perfect. Thanks.
