### ISSUE TITLE
Doesn't launch, crashes.

### ISSUE THREAD

**Issue by 4193883-eng** [AsahiLinux/muvm#85]
Hi, first of all wanted to thank you for all your contributions to the mac ecosystem.

So, I don't really don't know what logs to provide(but please do tell), but it errors out with this:
```

vsevolodlavrusha@fedora:~$ muvm -- sh
Error: Failed to mount filesystems, bailing out

Caused by:
    0: Failed to move_mount tmp to etc
    1: No such file or directory (os error 2)

```

**Comment by DmitrySboychakov** [comment]
Same here.

**Comment by m1m1k4tz** [comment]
I’ve come across this too and the workaround was to install it inside of a container

**Comment by slp** [comment]
Could you please paste the output of `ls -l /etc/resolv.conf` ?

**Comment by juanramirezc2** [comment]
i'm getting 
```bash
?127 ~ % ❯ muvm -- sh
No IPv6 nameserver available for NDP/DHCPv6
Error: Failed to mount filesystems, bailing out

Caused by:
    0: Failed to move_mount tmp to etc
    1: No such file or directory (os error 2)
```

@slp i'm getting this

```bash
 % ❯ls -l /etc/resolv.conf
-rw-r--r--. 1 systemd-resolve 920 Oct 16 08:47 /etc/resolv.conf
```

**Comment by juanramirezc2** [comment]
I updated to `0.1.3-1.fc40` and this is not an issue anymore :+1:

**Comment by 4193883-eng** [comment]
after an update everuthing works
